services:
  redis:
    image: redis:7
    container_name: journiv-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  journiv:
    image: swalabtech/journiv-app:latest
    container_name: journiv
    ports:
      # if you want to expose on a different port, change the left hand side of colon to the port
      # you want to expose on do not change the 8000 on the right hand side
      - "8000:8000"
    environment:
      - SECRET_KEY=your-secret-key-here # (REQUIRED) Replace with a strong secret key
      - DOMAIN_NAME=192.168.1.1 # (REQUIRED) Your server IP or domain
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - journiv_data:/data
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  celery-worker:
    image: swalabtech/journiv-app:latest
    container_name: journiv-celery-worker
    command: celery -A app.core.celery_app worker --loglevel=info
    environment:
      - SECRET_KEY=your-secret-key-here
      - DOMAIN_NAME=192.168.1.1
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - journiv_data:/data
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  journiv_data:
  redis_data:
